[package]
name = "rust_game"
version = "0.0.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
glam = "0.29.0"
lazy_static = "1.5.0"
log = "0.4.22"
palette = "0.7.6"
rayon = "1.10.0"
termsize = "0.1.9"

[profile.release]
opt-level = 2
lto = true
