name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rust_game(ubuntu)
        path: target/release/rust_game

  Windows:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rust_game(ubuntu)
        path: target/release/rust_game.exe
