name: Build Develop

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
      cargo update
      cargo b -r

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rust_game(windows).exe
        path: target/release
  
  macOS:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
      cargo update
      cargo b -r

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rust_game(macOS)
        path: target/release